# Generated by Django 2.1.7 on 2019-04-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='aid_provider',
        ),
        migrations.AddField(
            model_name='situation',
            name='aid_provider',
            field=models.ManyToManyField(to='idp_app.AidProvider'),
        ),
    ]
